### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ShafiqSadat** [dotcypress/mtproxy#1]
Compiling mtproxy v0.0.1 (file:///home/userName/mtproxy)
error: paths in `use` groups are experimental (see issue #44494)
 --> src/proto.rs:3:15
  |
3 | use std::{io, net::SocketAddr};
  |               ^^^^^^^^^^^^^^^

error: nested groups in `use` are experimental (see issue #44494)
 --> src/proto.rs:7:3
  |
7 |   aes::{self, KeySize}, symmetriccipher::SynchronousStreamCipher,
  |   ^^^^^^^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proto.rs:7:25
  |
7 |   aes::{self, KeySize}, symmetriccipher::SynchronousStreamCipher,
  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proto.rs:9:14
  |
9 | use crypto::{digest::Digest, sha2::Sha256};
  |              ^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proto.rs:9:30
  |
9 | use crypto::{digest::Digest, sha2::Sha256};
  |                              ^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proxy.rs:2:3
  |
2 |   cell::RefCell, collections::{HashMap, HashSet}, io::{self, ErrorKind}, net::SocketAddr, thread,
  |   ^^^^^^^^^^^^^

error: nested groups in `use` are experimental (see issue #44494)
 --> src/proxy.rs:2:18
  |
2 |   cell::RefCell, collections::{HashMap, HashSet}, io::{self, ErrorKind}, net::SocketAddr, thread,
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: nested groups in `use` are experimental (see issue #44494)
 --> src/proxy.rs:2:51
  |
2 |   cell::RefCell, collections::{HashMap, HashSet}, io::{self, ErrorKind}, net::SocketAddr, thread,
  |                                                   ^^^^^^^^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proxy.rs:2:74
  |
2 |   cell::RefCell, collections::{HashMap, HashSet}, io::{self, ErrorKind}, net::SocketAddr, thread,
  |                                                                          ^^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proxy.rs:3:3
  |
3 |   time::Duration, usize,
  |   ^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proxy.rs:6:14
  |
6 | use crypto::{digest::Digest, sha2::Sha256};
  |              ^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proxy.rs:6:30
  |
6 | use crypto::{digest::Digest, sha2::Sha256};
  |                              ^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proxy.rs:7:11
  |
7 | use mio::{net::TcpListener, unix::UnixReady, Events, Poll, PollOpt, Ready, Token};
  |           ^^^^^^^^^^^^^^^^

error: paths in `use` groups are experimental (see issue #44494)
 --> src/proxy.rs:7:29
  |
7 | use mio::{net::TcpListener, unix::UnixReady, Events, Poll, PollOpt, Ready, Token};
  |                             ^^^^^^^^^^^^^^^

error: nested groups in `use` are experimental (see issue #44494)
 --> src/pump.rs:2:3
  |
2 |   io::{self, prelude::*}, mem, u16,
  |   ^^^^^^^^^^^^^^^^^^^^^^

error: glob imports in `use` groups are experimental (see issue #44494)
 --> src/pump.rs:2:14
  |
2 |   io::{self, prelude::*}, mem, u16,
  |              ^^^^^^^^^^

error: aborting due to 16 previous errors

error: Could not compile `mtproxy`.

To learn more, run the command again with --verbose.

**Comment by hadi77ir** [comment]
Which toolchain are you using?

**Comment by JrooTJunior** [comment]
`nightly` toolchain is required.

**Comment by ShafiqSadat** [comment]
how i can install it?

**Comment by JrooTJunior** [comment]
```bash
$ rustup install nightly
$ rustup default nightly
```

**Comment by SayedSadat** [comment]
root@static:~# rustup install nightly
rustup: command not found

**Comment by dotcypress** [comment]
@SayedSadat latest stable Rust (1.26.0) is required
