### ISSUE TITLE
Error on compiling mtproxy

### ISSUE THREAD

**Issue by erfanghobadian** [dotcypress/mtproxy#2]
Hi 
I used both methods for compiling but reach the same error 
![3081ff14-3533-4305-858a-e32f34ec846e](https://user-images.githubusercontent.com/39496708/40497704-2abfd92e-5f92-11e8-94cf-f61ad3a4c072.jpeg)

**Comment by dotcypress** [comment]
@erfanghobadian  latest stable Rust (1.26.0) is required
