### ISSUE TITLE
not stable

### ISSUE THREAD

**Issue by amin1softco** [dotcypress/mtproxy#3]
after 3-4 disconnect and reconnection not connect again .
and eating cpu.

**Comment by amin1softco** [comment]
![image](https://user-images.githubusercontent.com/11088597/40549847-c7cd8548-604d-11e8-846d-7721c965f1f2.png)
not accept new connection after 5 minute of running...

**Comment by amin1softco** [comment]
i write this script seems work good 
````#!/bin/bash
while true                        #begin infinite loop (you'll have to manually kill)
do
  mtproxy -s 'ahmad' &                   #execute myprogram and background
  PID=$!                          #get PID of myprogram
  sleep 120                      #sleep 2 minutes (2m might work as parameter)
  kill -9 $PID                    #kill myprogram
done

**Comment by dotcypress** [comment]
@amin1softco work in progress, stable version will be published after Telegram releases `MTProxy` feature.
